name: assignment_hnd51_shinewaiyanaung
description: "GUSGO"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_segmented_tab_control: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer:
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - profilePicture/FemaleLecturerPic.png
    - profilePicture/MaleLecturerPic.png
    - Lectures/APDP/APDPintro.pdf
    - Lectures/APDP/APDPLecture1.pdf
    - Lectures/APDP/APDPLecture2.pdf
    - Lectures/APDP/APDPLecture3.pdf
    - Lectures/BPS/BPSintro.pdf
    - Lectures/BPS/BPSLecture1.pdf
    - Lectures/BPS/BPSLecture2.pdf
    - Lectures/BPS/BPSLecture3.pdf
    - Lectures/CRP/CRPintro.pdf
    - Lectures/CRP/CRPLecture.pdf
    - Lectures/CRP/CRPLecture2.pdf
    - Lectures/CRP/CRPLecture3.pdf
    - Lectures/IOT/IOTintro.pdf
    - Lectures/IOT/IOTLecture1.pdf
    - Lectures/IOT/IOTLecture2.pdf
    - Lectures/IOT/IOTLecture3.pdf
    - LectureImage/IOTImage.png
    - LectureImage/BPSImage.png
    - LectureImage/CRPImage.png
    - LectureImage/PADPImage.png
    - AppImages/PersonIcon/maleStudent.png
    - AppImages/UniversityIcon/GUSGO.png
    - AppImages/BackIcon/backButton.png
    - jsonDataApp/jsonData.json
    - AppImages/SignBackGround/SignBackGround.png

  fonts:
    - family: PrimaryFont
      fonts:
        - asset: fonts/primary_fonts/InknutAntiqua.ttf
    - family: SecondaryFont
      fonts:
        - asset: fonts/primary_fonts/IBMPlexMono.ttf
